export const GET_ATTENDANCE_DATA_SUCCESS = 'GET_ATTENDANCE_DATA_SUCCESS';
export const GET_ATTENDANCE_DATA_FAILURE = 'GET_ATTENDANCE_DATA_FAILURE';
export const CREATE_ATTENDANCE_DATA_SUCCESS = 'CREATE_ATTENDANCE_DATA_SUCCESS';
export const CREATE_ATTENDANCE_DATA_FAILURE = 'CREATE_ATTENDANCE_DATA_FAILURE';
export const UPDATE_ATTENDANCE_DATA_SUCCESS = 'UPDATE_ATTENDANCE_DATA_SUCCESS';
export const UPDATE_ATTENDANCE_DATA_FAILURE = 'UPDATE_ATTENDANCE_DATA_FAILURE';
export const DELETE_ATTENDANCE_DATA_SUCCESS = 'DELETE_ATTENDANCE_DATA_SUCCESS';
export const DELETE_ATTENDANCE_DATA_FAILURE = 'DELETE_ATTENDANCE_DATA_FAILURE';
