export const GET_POSITION_DATA_SUCCESS = 'GET_POSITION_DATA_SUCCESS';
export const GET_POSITION_DATA_FAILURE = 'GET_POSITION_DATA_FAILURE';
export const CREATE_POSITION_DATA_SUCCESS = 'CREATE_POSITION_DATA_SUCCESS';
export const CREATE_POSITION_DATA_FAILURE = 'CREATE_POSITION_DATA_FAILURE';
export const UPDATE_POSITION_DATA_SUCCESS = 'UPDATE_POSITION_DATA_SUCCESS';
export const UPDATE_POSITION_DATA_FAILURE = 'UPDATE_POSITION_DATA_FAILURE';
export const DELETE_POSITION_DATA_SUCCESS = 'DELETE_POSITION_DATA_SUCCESS';
export const DELETE_POSITION_DATA_FAILURE = 'DELETE_POSITION_DATA_FAILURE';
