export const GET_DEDUCTION_DATA_SUCCESS = 'GET_DEDUCTION_DATA_SUCCESS';
export const GET_DEDUCTION_DATA_FAILURE = 'GET_DEDUCTION_DATA_FAILURE';
export const CREATE_DEDUCTION_DATA_SUCCESS = 'CREATE_DEDUCTION_DATA_SUCCESS';
export const CREATE_DEDUCTION_DATA_FAILURE = 'CREATE_DEDUCTION_DATA_FAILURE';
export const UPDATE_DEDUCTION_DATA_SUCCESS = 'UPDATE_DEDUCTION_DATA_SUCCESS';
export const UPDATE_DEDUCTION_DATA_FAILURE = 'UPDATE_DEDUCTION_DATA_FAILURE';
export const DELETE_DEDUCTION_DATA_SUCCESS = 'DELETE_DEDUCTION_DATA_SUCCESS';
export const DELETE_DEDUCTION_DATA_FAILURE = 'DELETE_DEDUCTION_DATA_FAILURE';
